server:
  port: 8080
logging:
  level:
    cn.qianyu: debug
spring:
  datasource:x
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/helloworld
    username: helloworld
    password: eeFkAr8ZJRwNf2Sy
#    username: root
#    password: root


mybatis:
  type-aliases-package: cn.qianyu.domain